// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQm1KnFRKzrqfkEznWYB5VeSZ1ab7G1A',
    appId: '1:677070278719:web:23c8aa880c2a37bd47a88a',
    messagingSenderId: '677070278719',
    projectId: 'bankapp-98107',
    authDomain: 'bankapp-98107.firebaseapp.com',
    storageBucket: 'bankapp-98107.firebasestorage.app',
    measurementId: 'G-W09W99F8X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1L-RWNDwbuAIpx2iBUPLjPochfZZoDLM',
    appId: '1:677070278719:android:940ea75232384e1a47a88a',
    messagingSenderId: '677070278719',
    projectId: 'bankapp-98107',
    storageBucket: 'bankapp-98107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhY8obwnVvhvMftgFQXfmFX0XAgQmIX0o',
    appId: '1:677070278719:ios:5f3576e3402a336247a88a',
    messagingSenderId: '677070278719',
    projectId: 'bankapp-98107',
    storageBucket: 'bankapp-98107.firebasestorage.app',
    iosBundleId: 'com.we.bankapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhY8obwnVvhvMftgFQXfmFX0XAgQmIX0o',
    appId: '1:677070278719:ios:5f3576e3402a336247a88a',
    messagingSenderId: '677070278719',
    projectId: 'bankapp-98107',
    storageBucket: 'bankapp-98107.firebasestorage.app',
    iosBundleId: 'com.we.bankapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhQm1KnFRKzrqfkEznWYB5VeSZ1ab7G1A',
    appId: '1:677070278719:web:76dfe6341570ab8747a88a',
    messagingSenderId: '677070278719',
    projectId: 'bankapp-98107',
    authDomain: 'bankapp-98107.firebaseapp.com',
    storageBucket: 'bankapp-98107.firebasestorage.app',
    measurementId: 'G-8V6ZRRQ7TT',
  );

}